// jobs.js
// Fetches job postings from jobs.json (generated by GitHub Actions) and renders each as a styled card

const JOBS_JSON_URL = '../jobs.json';
let allJobs = [];
let filteredJobs = [];

// Extract clean location from messy location string
function extractLocation(locationStr) {
    if (!locationStr) return 'Location TBA';
    
    // Remove tags section and timestamps
    let cleaned = locationStr
        .split(/\s*Tags?:/i)[0]  // Remove "Tags:" section
        .split(/\d+\s*(hours?|days?|weeks?)\s*ago/i)[0]  // Remove timestamps
        .split(/\s+View\s*$/i)[0]  // Remove trailing "View" button text
        .trim();
    
    // Extract city, state pattern from parentheses like "(City, State)"
    const stateMatch = cleaned.match(/\(([^,]+),\s*([^)]+)\)/);
    if (stateMatch) {
        const city = stateMatch[1].trim();
        const state = stateMatch[2].trim();
        return `${city}, ${state}`;
    }
    
    // Fallback: take cleaned string up to first parenthesis or return as-is
    const beforeParen = cleaned.split('(')[0].trim();
    return beforeParen || 'Location TBA';
}

// Auto-categorize jobs based on title and description
function categorizeJob(job) {
    const text = `${job.title} ${job.description}`.toLowerCase();
    
    if (text.includes('internship') || text.includes('intern')) {
        return 'Internship';
    }
    if (text.includes('technician') || text.includes('tech')) {
        return 'Technician';
    }
    if (text.includes('professor') || text.includes('faculty')) {
        return 'Professor';
    }
    if (text.includes('graduate') || text.includes('graduate teaching') || text.includes('m.s.') || text.includes('ph.d.') || text.includes('mastership')) {
        return 'Graduate';
    }
    if (text.includes('postdoc') || text.includes('post-doc')) {
        return 'Postdoc';
    }
    return 'Full-time';
}

// Get unique locations from jobs
function getLocations(jobs) {
    const locations = new Set();
    jobs.forEach(job => {
        const loc = extractLocation(job.location);
        if (loc !== 'Location TBA') {
            const state = loc.split(', ')[1];
            if (state) locations.add(state);
        }
    });
    return Array.from(locations).sort();
}

// Render filter UI
function renderFilters(jobs) {
    const filterContainer = document.getElementById('filter-container');
    if (!filterContainer) return;
    
    const categories = ['All', 'Full-time', 'Internship', 'Technician', 'Professor', 'Graduate', 'Postdoc'];
    const locations = ['All States', ...getLocations(jobs)];
    
    // Category buttons
    const categoryDiv = document.createElement('div');
    categoryDiv.className = 'filter-group';
    const categoryLabel = document.createElement('span');
    categoryLabel.className = 'filter-label';
    categoryLabel.textContent = 'Category:';
    categoryDiv.appendChild(categoryLabel);
    
    categories.forEach(cat => {
        const btn = document.createElement('button');
        btn.className = 'filter-btn';
        if (cat === 'All') btn.classList.add('active');
        btn.textContent = cat;
        btn.onclick = () => filterJobs('category', cat);
        categoryDiv.appendChild(btn);
    });
    
    // Location dropdown
    const locDiv = document.createElement('div');
    locDiv.className = 'filter-group';
    const locLabel = document.createElement('span');
    locLabel.className = 'filter-label';
    locLabel.textContent = 'State:';
    locDiv.appendChild(locLabel);
    
    const select = document.createElement('select');
    select.className = 'filter-select';
    select.onchange = (e) => filterJobs('location', e.target.value);
    
    locations.forEach(loc => {
        const opt = document.createElement('option');
        opt.value = loc;
        opt.textContent = loc;
        select.appendChild(opt);
    });
    locDiv.appendChild(select);
    
    filterContainer.appendChild(categoryDiv);
    filterContainer.appendChild(locDiv);
}

// Filter and re-render jobs
function filterJobs(filterType, filterValue) {
    const categoryBtns = document.querySelectorAll('.filter-btn');
    const locSelect = document.querySelector('.filter-select');
    
    let selectedCategory = 'All';
    let selectedLocation = 'All States';
    
    // Get current filter values
    categoryBtns.forEach(btn => {
        if (btn.classList.contains('active')) {
            selectedCategory = btn.textContent;
        }
    });
    selectedLocation = locSelect?.value || 'All States';
    
    // Update active button
    if (filterType === 'category') {
        categoryBtns.forEach(btn => btn.classList.remove('active'));
        Array.from(categoryBtns).find(btn => btn.textContent === filterValue)?.classList.add('active');
        selectedCategory = filterValue;
    }
    
    // Apply filters
    filteredJobs = allJobs.filter(job => {
        const category = categorizeJob(job);
        const location = extractLocation(job.location);
        const state = location.split(', ')[1];
        
        const categoryMatch = selectedCategory === 'All' || category === selectedCategory;
        const locationMatch = selectedLocation === 'All States' || state === selectedLocation;
        
        return categoryMatch && locationMatch;
    });
    
    renderJobs(filteredJobs);
}

// Render job cards
function renderJobs(jobs) {
    const jobsList = document.getElementById('jobs-list');
    jobsList.innerHTML = '';
    
    if (jobs.length === 0) {
        jobsList.innerHTML = '<p style="grid-column: 1/-1; text-align: center;">No jobs found matching your filters.</p>';
        return;
    }
    
    const grid = document.createElement('div');
    grid.className = 'jobs-grid';
    
    jobs.forEach(job => {
        const card = document.createElement('article');
        card.className = 'job-card';
        const category = categorizeJob(job);
        
        // Category badge
        const badge = document.createElement('div');
        badge.className = `job-badge badge-${category.toLowerCase().replace('-', '')}`;
        badge.textContent = category;
        
        // Title
        const h3 = document.createElement('h3');
        const a = document.createElement('a');
        a.href = job.link || '#';
        a.target = '_blank';
        a.rel = 'noopener';
        a.textContent = job.title || 'No title';
        h3.appendChild(a);
        
        // Organization (from description)
        const org = document.createElement('div');
        org.className = 'job-organization';
        org.textContent = job.description || '';
        
        // Location
        const loc = document.createElement('div');
        loc.className = 'job-location';
        loc.textContent = extractLocation(job.location);
        
        // Footer with button
        const footer = document.createElement('div');
        footer.className = 'job-footer';
        const viewLink = document.createElement('a');
        viewLink.href = job.link || '#';
        viewLink.target = '_blank';
        viewLink.rel = 'noopener';
        viewLink.className = 'job-apply';
        viewLink.textContent = 'View posting';
        footer.appendChild(viewLink);
        
        card.appendChild(badge);
        card.appendChild(h3);
        card.appendChild(org);
        card.appendChild(loc);
        card.appendChild(footer);
        
        grid.appendChild(card);
    });
    
    jobsList.appendChild(grid);
    
    // Scroll to results
    document.querySelector('section')?.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
}

async function fetchJobs() {
    const loading = document.getElementById('loading');
    const jobsList = document.getElementById('jobs-list');
    loading.style.display = 'block';
    jobsList.innerHTML = '';
    
    try {
        const response = await fetch(JOBS_JSON_URL);
        if (!response.ok) {
            throw new Error(`Failed to fetch jobs (status ${response.status})`);
        }
        
        allJobs = await response.json();
        
        if (!Array.isArray(allJobs) || allJobs.length === 0) {
            jobsList.innerHTML = '<p>No jobs found.</p>';
            return;
        }
        
        filteredJobs = allJobs;
        renderFilters(allJobs);
        renderJobs(filteredJobs);
        
    } catch (error) {
        jobsList.innerHTML = `<p>Could not load jobs. ${error && error.message ? error.message : ''}</p>`;
    } finally {
        loading.style.display = 'none';
    }
}

document.addEventListener('DOMContentLoaded', fetchJobs);